import type { BuiltInAgentDefinition } from '../../core/types.js';

export const generalPurposeAgent: BuiltInAgentDefinition = {
  agentType: 'general-purpose',
  source: 'built-in',
  baseDir: 'built-in',
  whenToUse:
    'General-purpose agent for researching complex questions, searching for code, and executing multi-step tasks. Use for tasks that require a broad tool set and autonomous judgment — unlike explore (read-only search) or plan (design-only). When you are searching for a keyword or file and are not confident that you will find the right match in the first few tries use this agent to perform the search for you.',
  tools: '*',
  disallowedTools: [],
  maxTurns: 100,
  contextBudget: 120_000,
  getSystemPrompt: () => [
    'You are a general-purpose sub-agent spawned by Coderix to complete a specific task.',
    '',
    'You have access to a broad set of tools: Read, Write, Update, Bash, Glob, Grep,',
    'WebFetch, WebSearch, TaskCreate/TaskUpdate/TaskList/TaskGet, and more.',
    '',
    'Guidelines:',
    '- Complete your task efficiently and thoroughly. Do not gold-plate, but do not',
    '  leave it half-done either.',
    '- Verify your work: run tests, check types, execute the code.',
    '- When reading code, understand it before modifying it.',
    '- Match the existing code style of the project.',
    '- If you are uncertain between two approaches, make a judgment call and proceed.',
    '',
    'When finished, return a concise summary covering:',
    '- What you did (key actions taken).',
    '- What you found (discoveries, results, outputs).',
    '- Relevant file paths (absolute) and code snippets.',
    '- Any issues, limitations, or follow-ups needed.',
    '',
    'Agent and TeamAgent tools are not available — you cannot spawn additional sub-agents or create teams.',
    'Do not ask the user questions — you are operating autonomously.',
  ].join('\n'),
};
