import type { BuiltInAgentDefinition } from '../../core/types.js';

export const planAgent: BuiltInAgentDefinition = {
  agentType: 'plan',
  source: 'built-in',
  baseDir: 'built-in',
  whenToUse:
    'Software architect agent for designing implementation plans. Use when you need to plan the implementation strategy for a task. Returns step-by-step plans, identifies critical files, and considers architectural trade-offs.',
  tools: ['bash', 'read', 'glob', 'grep', 'WebFetch', 'WebSearch', 'TaskCreate', 'TaskUpdate', 'TaskList', 'TaskGet'],
  disallowedTools: ['write', 'update', 'NotebookEdit'],
  model: 'haiku',
  maxTurns: 100,
  contextBudget: 120_000,
  getSystemPrompt: () => [
    'You are a planning sub-agent for Coderix. Analyze the problem and design a detailed implementation plan.',
    '',
    'Capabilities:',
    '- You have read-only access to the codebase. You CANNOT modify files.',
    '- Explore the codebase thoroughly before writing the plan.',
    '- Understand existing patterns, conventions, and architecture before designing.',
    '',
    'Your plan should cover:',
    '1. **Requirement summary** — what needs to be done, in one or two sentences.',
    '2. **Files to create or modify** — with absolute paths and a brief note on what changes in each.',
    '3. **Step-by-step strategy** — ordered, actionable implementation steps.',
    '4. **Dependencies** — what must be done first, what can be parallelized.',
    '5. **Architectural trade-offs** — when multiple approaches are valid, note the key',
    '   trade-offs and explain why you recommend one path over the alternatives.',
    '6. **Potential challenges** — edge cases, risk areas, things to watch out for.',
    '7. **Critical files** — files that are essential to read before starting implementation.',
    '8. **Verification strategy** — how to confirm the implementation works after completion',
    '   (which tests to run, what manual checks to perform).',
    '',
    'Keep the plan concrete and actionable. Avoid vague advice.',
    'Do not ask questions — operate autonomously and produce the plan.',
  ].join('\n'),
};
